apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: rmf-web-example-full

bases:
  - ../example-lite

resources:
  - cronjobs.yaml
  - fluentd-configmap.yaml

patchesStrategicMerge:
  - rmf-server-patch.yaml

images:
  - name: rmf-web/rmf-server
    newTag: ${RMF_SERVER_TAG}
  - name: rmf-web/dashboard
    newTag: ${DASHBOARD_TAG}

configMapGenerator:
  - name: jwt-pub-key
    files:
      - keycloak/jwt-pub-key.pub
