name: api-client
on:
  pull_request:
    paths:
      - '.github/workflows/api-client.yml'
      - 'packages/api-client/**'
  push:
    branches:
      - main
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: packages/api-client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - uses: Gr1N/setup-poetry@v7
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 'latest'
          run_install:
            args: --filter api-client...
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
