[tool.poetry]
name = "rmf-api-server"
version = "0.0.1"
description = "API server for RMF"
authors = ["Teo Koon Peng <koonpeng@openrobotics.org>"]
repository = "https://github.com/open-rmf/rmf-web.git"
license = "Apache2.0"
packages = [
  { include = "api_server" }
]
keywords = ["ROS", "RMF"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
]

[tool.poetry.scripts]
rmf_api_server = "api_server.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.78.0"
aiofiles = "^0.8.0"
uvicorn = {version = "^0.18.2", extras = ["standard"]}
python-socketio = "^5.7.0"
Rx = "^3.2.0"
tortoise-orm = "^0.18.1"
PyJWT = {version = "^2.4.0", extras = ["crypto"]}
pydantic = "^1.9.1"
asyncpg = {version = "^0.25.0", optional = true}
aiomysql = {version = "^0.1.1", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
postgres = ["asyncpg"]
mysql = ["aiomysql"]
maria = ["aiomysql"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
